version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web.docker
    container_name: lumen_web
    image: lumen_web
    volumes:
      - ../:/var/www
    ports:
      - 8084:80
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: ./app.docker
    container_name: lumen_app
    image: lumen_app
    volumes:
      - ../:/var/www
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "33066:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network
  node:
    build:
      context: .
      dockerfile: ./node.docker
    container_name: node
    command: ["./wait-for-it.sh", "mongo_db:27017", "--", "npm", "run-script", "docker:start"]
    volumes:
      - ./:/home/node/app
      - ./wait-for-it.sh:/home/node/app/wait-for-it.sh
    links:
      - mongo_db
    ports:
      - 4001:4000
    networks:
      - app-network
  mongo_db:
    image: mongo:4.4.3-bionic
    container_name: mongo_db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  mongodb: {}
  mongoconfig: {}
